name: Deploy to Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      TF_VAR_env: ${{ vars.ENV_VARIABLE }}
    steps:
    - name: Use variables
      run: |
        echo "TF ENV ENR : $TF_VAR_env"
    - name: Output the variable
      run: echo "::set-output name=TF_VAR_env::$TF_VAR_env"
  second_job:
    name: Second Job
    runs-on: ubuntu-latest
    needs: deploy  # Specify dependency on the first job
    steps:
    - name: Use the variable
      run: echo "TF_VAR_env in second job: ${{ needs.deploy.outputs.TF_VAR_env }}"
