name: Deploy to Nowhere
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - prod
          
env:
  deploy-a: ${{ vars.a }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      TF_VAR_env: ${{ vars.ENV_VARIABLE }}
    steps:
    - name: Use variables
      run: |
        echo "TF ENV ENR : $TF_VAR_env"
    - name: Output the variable
      run: echo "::set-output name=TF_VAR_env::$TF_VAR_env"
  another_job:
    name: Another Job
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Reuse TF_VAR_env in Another Job
        run:  |
          echo "TF VAR ENV in env Job: ${{ env.deploy.a }}
